# Importing Libraries 

In [3]:
import numpy as np
import pandas as pd

# Importing Dataset

In [4]:
dataset=pd.read_csv('cp.txt')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [5]:
dataset.head()

Age  Gender                         Stream  Internships  CGPA  Hostel  \
0   22    Male  Electronics And Communication            1     8       1   
1   21  Female               Computer Science            0     7       1   
2   22  Female         Information Technology            1     6       0   
3   21    Male         Information Technology            0     8       0   
4   22    Male                     Mechanical            0     8       1   

   HistoryOfBacklogs  PlacedOrNot  
0                  1            1  
1                  1            1  
2                  0            1  
3                  1            1  
4                  0            1

In [6]:
print(x)

[[22 'Male' 'Electronics And Communication' 1 8 1 1]
 [21 'Female' 'Computer Science' 0 7 1 1]
 [22 'Female' 'Information Technology' 1 6 0 0]
 [21 'Male' 'Information Technology' 0 8 0 1]
 [22 'Male' 'Mechanical' 0 8 1 0]
 [22 'Male' 'Electronics And Communication' 0 6 0 0]
 [21 'Male' 'Computer Science' 0 7 0 1]
 [21 'Male' 'Information Technology' 1 7 0 0]
 [21 'Male' 'Computer Science' 2 6 0 0]
 [21 'Female' 'Computer Science' 1 6 1 0]
 [22 'Male' 'Computer Science' 1 7 0 0]
 [22 'Female' 'Electrical' 1 8 0 1]
 [21 'Female' 'Computer Science' 2 6 1 1]
 [21 'Male' 'Computer Science' 1 8 0 1]
 [21 'Female' 'Electronics And Communication' 2 8 0 0]
 [22 'Male' 'Mechanical' 0 8 1 0]
 [22 'Female' 'Computer Science' 1 7 1 0]
 [21 'Male' 'Civil' 0 6 0 0]
 [21 'Male' 'Computer Science' 1 7 0 0]]


In [7]:
print(y)

[1 1 1 1 1 0 0 0 1 0 0 1 0 1 1 1 0 0 0]


# Data Pre-Processing

# Dataset Cleaning

In [8]:
dataset.isnull().sum()

Age                  0
Gender               0
Stream               0
Internships          0
CGPA                 0
Hostel               0
HistoryOfBacklogs    0
PlacedOrNot          0
dtype: int64

# Label Encoding

In [9]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
le2=LabelEncoder()
le=LabelEncoder()
x[:,1]=le1.fit_transform(x[:,1])
x[:,2]=le2.fit_transform(x[:,2])

In [12]:
print(x)

[[22 1 3 1 8 1 1]
 [21 0 1 0 7 1 1]
 [22 0 4 1 6 0 0]
 [21 1 4 0 8 0 1]
 [22 1 5 0 8 1 0]
 [22 1 3 0 6 0 0]
 [21 1 1 0 7 0 1]
 [21 1 4 1 7 0 0]
 [21 1 1 2 6 0 0]
 [21 0 1 1 6 1 0]
 [22 1 1 1 7 0 0]
 [22 0 2 1 8 0 1]
 [21 0 1 2 6 1 1]
 [21 1 1 1 8 0 1]
 [21 0 3 2 8 0 0]
 [22 1 5 0 8 1 0]
 [22 0 1 1 7 1 0]
 [21 1 0 0 6 0 0]
 [21 1 1 1 7 0 0]]


In [11]:
dataset.head(10)

Age  Gender                         Stream  Internships  CGPA  Hostel  \
0   22    Male  Electronics And Communication            1     8       1   
1   21  Female               Computer Science            0     7       1   
2   22  Female         Information Technology            1     6       0   
3   21    Male         Information Technology            0     8       0   
4   22    Male                     Mechanical            0     8       1   
5   22    Male  Electronics And Communication            0     6       0   
6   21    Male               Computer Science            0     7       0   
7   21    Male         Information Technology            1     7       0   
8   21    Male               Computer Science            2     6       0   
9   21  Female               Computer Science            1     6       1   

   HistoryOfBacklogs  PlacedOrNot  
0                  1            1  
1                  1            1  
2                  0            1  
3                  1            1  
4                  0            1  
5                  0            0  
6                  1            0  
7                  0            0  
8                  0            1  
9                  0            0

# Splitting Dataset into Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=0)

# Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

# Training Dataset

In [ ]:
from xgboost import XGBClassifier
classifier=XGBClassifier()
classifier.fit(X_train,Y_train)

# Validation

# 1. Making Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred=classifier.predict(X_test)
cm=confusion_matrix(Y_test,y_pred)
print(cm)
accuracy_score(Y_test,y_pred)

# 2. Applying K-fold Cross Validation

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies=cross_val_score(estimator=classifier,X=X_train,y=Y_train,cv=10)
print('Accuracy: {:.2f} Standard Deviation: {:.2f}'.format(accuracies.mean()*100,accuracies.std()*100))

# 3. Predicting Test set Result

In [ ]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

# Single Prediction

In [ ]:
result=classifier.predict(sc.transform([[22,0,0,1,8,1,1]]))
if result==[1]:
  print('Person is Placed')
else:
  print('Person is not Placed')

#  we will create our prediction() with @anvil.server.callable decorator. The decerator makes the function callable from anvil app.

In [ ]:
@anvil.server.callable
def prediction(age, gender, stream, internship, cgpa, hostel, HistoryOfBacklogs):
    out = classifier.predict(sc.transform([[age, gender, stream, internship, cgpa, hostel, HistoryOfBacklogs]]))
    print(out)
    return out